### ISSUE TITLE
Update blobs for 4.6

### ISSUE THREAD

**Issue by tejaycar** [cloudfoundry-community/mattermost-boshrelease#15]
@drnic can you please run the jobs to update the blobs for the recent MM 4.6 release?  also, the load test repo should have version tags now.

**Comment by drnic** [comment]
Thanks for the reminder. I turned off the https://ci-ohio.starkandwayne.com/teams/cfcommunity/pipelines/mattermost-releases/jobs/check-version/builds/219 pipeline due to this error. I haven't made time yet to see what changed/why this pipeline `check-version` / `version` steps broke.

![screen shot 2018-01-20 at 11 46 15 am](https://user-images.githubusercontent.com/108/35178651-9192627e-fdd7-11e7-838c-42fe49e23d65.png)

**Comment by drnic** [comment]
Ok, fixed this issue now https://ci-ohio.starkandwayne.com/teams/cfcommunity/pipelines/mattermost-releases?groups=mattermost-releases
